# Site settings
title: Site Title
email: user@example.com
description: > # this means to ignore newlines until "baseurl:"
  I am the meta description. Edit me for Googley goodness.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: therhineland
github_username:  rhineland

# Build settings
markdown: kramdown
permalink: pretty